name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  verify:
    name: Create Release Draft
    runs-on: ubuntu-latest
    permissions:
        contents: write
    outputs:
      version:  ${{ steps.parse_package.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: Parse Package
        uses: actions/github-script@v7
        id: parse_package
        with:
          result-encoding: string
          script: |
            try {
              const package = require('./package.json');
              const version = package.version;
              core.setOutput('version', version);
              console.log("Package version:", version);
            } catch(error) {
              core.setFailed(error)
            }
      - name: Create Release Draft
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.parse_package.outputs.version }}
          draft: true
          prerelease: true
          allowUpdates: true
          updateOnlyUnreleased: true
          skipIfReleaseExists: true
          removeArtifacts: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
